apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jupyterhub
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jupyterhub
    namespace: jupyterhub
  userNames:
  - system:serviceaccount:jupyterhub:jupyterhub